Repository droidknights/DroidKnights2020_App, pull requests merged in 2020-02, with the labels that each got.

#15 Add, Github Template
  .github/ISSUE_TEMPLATE/basic-report.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#31 #30 - 나눔 스퀘어 폰트를 적용함.
  androidapp/app/src/main/res/font/nanum_square.xml
  androidapp/app/src/main/res/font/nanum_square_otf_bold.otf
  androidapp/app/src/main/res/font/nanum_square_otf_regular.otf
  androidapp/app/src/main/res/values/styles.xml
Labels: enhancement

#35 Contribute Guide 작성
  CONTRIBUTING.md
  README.md
Labels: documentation

#40 머테리얼 디자인 적용을 위한 앱 테마 변경
  androidapp/app/build.gradle
  androidapp/app/src/main/res/values/colors.xml
  androidapp/app/src/main/res/values/styles.xml
  androidapp/dependency.gradle
Labels: good first issue, welcome contribute

#60 Introduce Pre-packaged DB
  androidapp/app/build.gradle
  androidapp/app/src/main/java/com/droidknights/app2020/db/SessionRepositoryImpl.kt
  androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDb.kt
  androidapp/app/src/main/java/com/droidknights/app2020/db/prepackage/PrePackagedDbImpl.kt
  androidapp/app/src/main/java/com/droidknights/app2020/di/AppComponent.kt
  androidapp/app/src/main/java/com/droidknights/app2020/di/PrePackagedDbModule.kt
  androidapp/dependency.gradle
Labels: awesome
